name: .NET

on:
  push:
    branches: [ saga-command, main ]
  pull_request:
    branches: [ saga-command, main ]
    
  workflow_dispatch:
    inputs:
      reason:
        required: true
        default: 'Manual run'
    
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Setup test enviroment
      run: dotnet test --results-directory "test-results" --collect:"Code Coverage" --settings .runsettings
    - run: dotnet tool update --global dotnet-coverage
    - run: dotnet-coverage merge --output test-result.cobertura.xml --output-format cobertura "test-results/**/*.coverage"
    - run: dotnet tool install --global dotnet-reportgenerator-globaltool
    - run: reportgenerator -reports:test-result.cobertura.xml -targetdir:coverage-report -reporttypes:"MarkdownSummaryGithub"
    - run: cat coverage-report/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
